---
title: "Apple Health Data"
output: 
  html_notebook:
    toc: yes
---

```{r functions, include=FALSE}

library(tidyverse)
library(xml2)
library(scales)
library(glue)

cleanSourceName <- function(sourceName) {
  # Clean up source names (some seem to contain special characters)
  return(str_replace_all(sourceName, "[^A-Za-z0-9'’ ]", " "))
}

# To-Do: Make this faster!
getHealthData <- function(xmlData) {
  
  results <- xml_find_all(xmlData, "//Record") %>%
    map(xml_attrs) %>%
    map_df(as.list) %>%
    select(-device, -creationDate) %>%
    filter(!str_detect(type, "HKCategoryTypeIdentifier.*")) %>%
    mutate(
      type = str_replace_all(type, "HKQuantityTypeIdentifier", ""),
      sourceName = cleanSourceName(sourceName),
      startDate = ymd_hms(startDate),
      endDate = ymd_hms(endDate),
      value = as.numeric(value)
    )
  
  return(results)
}


getWorkoutData <- function(xmlData) {
  
  # At some point (iOS 16?) some of the workout attributes were moved from
  # "Workout" to "WorkoutStatistics" nodes. Pull them both and combine.
  
  results1 <- xml_find_all(xmlData, "//Workout",) %>%
    map(xml_attrs) %>%
    map_df(as.list)
  
  results2 <- xml_find_all(xmlData, "//Workout/WorkoutStatistics",) %>%
    map(xml_attrs) %>%
    map_df(as.list) %>%
    filter(type == "HKQuantityTypeIdentifierDistanceWalkingRunning") %>%
    select(startDate, endDate, distance = sum, distanceUnit = unit)
  
  combined <- results1 %>%
    left_join(results2, by = c("startDate", "endDate"))
  
  results <- combined %>%
    select(-device, -creationDate) %>%
    rename(activityType = workoutActivityType) %>%
    mutate(
      activityType = str_replace_all(activityType, "HKWorkoutActivityType", ""),
      sourceName = cleanSourceName(sourceName),
      duration = as.numeric(duration),
      distance = as.numeric(distance),
      startDate = ymd_hms(startDate),
      endDate = ymd_hms(endDate)
    )
  
  return(results)
}

```

```{r data_retrieval, include=FALSE}

outputDir <- "output"
dir.create(outputDir, showWarnings = FALSE)

filename <- "data/apple_health_export/export.xml"

message("Loading health data file ... ", appendLF = FALSE)
start_time <- Sys.time()
xmlData <- read_xml(filename)
message(glue("done, taking {format(difftime(Sys.time(), start_time))}"))

message("Parsing health data - buckle-up, this is gonna take a while ... ", appendLF = FALSE)
start_time <- Sys.time()
healthData <- getHealthData(xmlData) %>%
  mutate(startDate = with_tz(startDate, tzone = "US/Eastern"),
         endDate = with_tz(endDate, tzone = "US/Eastern"))
message(glue("done, taking {format(difftime(Sys.time(), start_time))}"))

minHealthDate <- min(healthData$endDate) %>% date()
maxHealthDate <- max(healthData$endDate) %>% date()

message("Parsing workout data ... ", appendLF = FALSE)
start_time <- Sys.time()
workoutData <- getWorkoutData(xmlData) %>%
  mutate(startDate = with_tz(startDate, tzone = "US/Eastern"),
         endDate = with_tz(endDate, tzone = "US/Eastern"))
message(glue("done, taking {format(difftime(Sys.time(), start_time))}"))

maxWorkoutDate <- max(workoutData$endDate) %>% date()

lastNewHikingBoots <- ymd("2022-04-14")

```

Report created: `r now() %>% with_tz(tzone = "US/Eastern") %>% format("%F %I:%M:%S %p %Z")`.
Includes data from `r minHealthDate` through `r maxHealthDate`.

## Steps and Distance
```{r steps_distance, echo=FALSE}

dailySteps <- healthData %>%
  filter(type == "StepCount") %>%
  transmute(date = date(endDate), sourceName, steps = value) %>%
  group_by(date, sourceName) %>%
  summarize(steps = sum(steps), .groups = "drop")

dailySteps %>% 
  filter(date >= maxHealthDate - months(2)) %>%
  ggplot(aes(x = date, y = steps, group = sourceName, color = sourceName)) +
    geom_line() +
    geom_smooth(method = 'loess', formula = 'y ~ x') +
    scale_x_date(breaks = pretty_breaks(n = 10), date_labels = "%b %e, '%y ") +
    scale_y_continuous(labels = comma) +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
    labs(title = "Daily steps")


dailyDistance <- healthData %>%
  filter(type == "DistanceWalkingRunning") %>%
  transmute(date = date(endDate), sourceName, distance = value) %>%
  group_by(date, sourceName) %>%
  summarize(distance = sum(distance), .groups = "drop")

dailyDistance %>% 
  filter(date >= maxHealthDate - months(2)) %>%
  ggplot(aes(x = date, y = distance, group = sourceName, color = sourceName)) +
    geom_line() +
    geom_smooth(method = 'loess', formula = 'y ~ x') +
    scale_x_date(breaks = pretty_breaks(n = 10), date_labels = "%b %e, '%y ") +
    scale_y_continuous(labels = comma) +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
    labs(title = "Daily distance",
         y = "miles")


dailyDistance %>%
  mutate(year = year(date)) %>%
  group_by(year, sourceName) %>%
  summarize(distance = sum(distance), .groups = "drop") %>%
  ggplot(aes(x = as.factor(year), y = distance, fill = sourceName, group = sourceName)) +
    geom_col(position = position_dodge2(preserve = "single")) +
    geom_text(aes(label = round(distance), vjust = "inward"), position = position_dodge2(width = 0.9)) +
    scale_y_continuous(expand = expansion(mult = c(0, .01))) +
    labs(title = "Yearly distance",
         x = "year",
         y = "miles")

```

## Blood Pressure
```{r blood_pressure, echo=FALSE}

bloodPressure <- healthData %>% 
  filter(sourceName %in% c("Health", "OmronWellness", "OMRON connect"), 
         type %in% c("BloodPressureSystolic", "BloodPressureDiastolic", "HeartRate")) %>%
  select(datetime = endDate, type, value) %>%
  # For some reason, blood pressure data seems duplicated
  distinct() %>%
  tidyr::spread(key = type, value = value) %>%
  select(datetime, systolic = BloodPressureSystolic, diastolic = BloodPressureDiastolic, pulse = HeartRate)

write.csv(bloodPressure, glue("{outputDir}/bloodPressure_{maxHealthDate}.csv"), row.names = FALSE)

colorSystolic <- rgb(0.7, 0.2, 0.1)
colorDiastolic <- rgb(0.2, 0.7, 0.1)
colorPulse <- "blue"

# Lollipop/dumbbell chart
bloodPressureGraph <- bloodPressure %>% 
  filter(datetime >= maxHealthDate - months(3))

if (nrow(bloodPressureGraph) >= 2) {
  ggplot(bloodPressureGraph, aes(x = datetime)) +
    geom_segment(aes(xend = datetime, y = diastolic, yend = systolic), color="grey") +
    geom_point(aes(y = systolic), color = colorSystolic, size = 3, alpha = 0.5) +
    geom_point(aes(y = diastolic), color = colorDiastolic, size = 3, alpha = 0.5) +
    geom_point(aes(y = pulse), color = colorPulse, size = 3, alpha = 0.5) +
    geom_smooth(aes(y = systolic), color = colorSystolic, linewidth = 0.6, alpha = 0.2) +
    geom_smooth(aes(y = diastolic), color = colorDiastolic, linewidth = 0.6, alpha = 0.2) +
    geom_smooth(aes(y = pulse), color = colorPulse, linewidth = 0.6, alpha = 0.2) +
    geom_text(data = bloodPressureGraph %>% filter(!is.na(systolic)) %>% filter(datetime == min(datetime)),
              aes(x = datetime, y = systolic, label = "systolic"),
              color = colorSystolic, size = 4, vjust = -1) +
    geom_text(data = bloodPressureGraph %>% filter(!is.na(diastolic)) %>% filter(datetime == min(datetime)), 
              aes(x = datetime, y = diastolic, label = "diastolic"), 
              color = colorDiastolic, size = 4, vjust = -1) +
    geom_text(data = bloodPressureGraph %>% filter(!is.na(pulse)) %>% filter(datetime == min(datetime)),
              aes(x = datetime, y = pulse, label = "pulse"),
              color = colorPulse, size = 4, vjust = -1) +
    scale_x_datetime(breaks = pretty_breaks(n = 10), date_labels = "%b %e, '%y ") +
    scale_y_continuous(breaks = pretty_breaks(n = 10)) +
    labs(title = "Blood pressure and pulse", x = "", y = "") +
    theme_light() +
    theme(panel.border = element_blank(),
          axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
}

```

## Workouts
```{r workouts, echo=FALSE}

dailyWorkoutSummary <- workoutData %>%
  mutate(day = floor_date(endDate, unit = "day"),
         day = as_date(day)) %>%
  group_by(day, activityType) %>%
  summarize(distance = sum(distance), .groups = "drop") %>%
  filter(distance > 0)

monthlyWorkoutSummary <- dailyWorkoutSummary %>%
  mutate(month = floor_date(day, unit = "month"),
         month = as_date(month)) %>%
  group_by(month, activityType) %>%
  summarize(distance = sum(distance), .groups = "drop") %>%
  filter(distance > 0)

ggplot(monthlyWorkoutSummary, aes(x = month, y = distance, fill = activityType)) +
  geom_col() +
  geom_text(aes(label = round(distance)), position = position_stack(vjust = .5), size = 3) +
  scale_x_date(breaks = pretty_breaks(n = n_distinct(monthlyWorkoutSummary$month) / 2)) +
  scale_y_continuous(breaks = pretty_breaks(n = 10), expand = expansion(mult = c(0, .01))) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  labs(title = "Monthly workout distance",
       y = "miles")

ggplot(monthlyWorkoutSummary, 
       aes(x = month, y = distance, color = activityType, fill  = activityType)) +
  geom_line() +
  geom_smooth(method = 'loess', formula = 'y ~ x') +
  scale_x_date(breaks = pretty_breaks(n = n_distinct(monthlyWorkoutSummary$month) / 2)) +
  scale_y_continuous(breaks = pretty_breaks(n = 10), expand = expansion(mult = c(0, .01))) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  labs(title = "Monthly workout distance",
       y = "miles")


```

### Hiking
Cumulative hiking distance since `r lastNewHikingBoots`: 
`r dailyWorkoutSummary %>%
     filter(day >= lastNewHikingBoots,
            activityType == 'Hiking') %>%
     pull(distance) %>%
     sum() %>%
     round()
` miles.
     
